### ISSUE TITLE
SDK Status

### ISSUE THREAD

**Issue by 0x3639** [ItsChaceD/zenon-android#1]
Hello

We are getting ready to move into the next phase of NoM and would like to update the status of all SDKs.  We hope things are going well for you.  

https://forum.zenon.org/t/zenon-sdk-status/414/33?u=0x3639

**Comment by ItsChaceD** [comment]
> Hello
> 
> We are getting ready to move into the next phase of NoM and would like to update the status of all SDKs. We hope things are going well for you.
> 
> https://forum.zenon.org/t/zenon-sdk-status/414/33?u=0x3639

Hello, things are going well. The Kotlin SDK is feature complete & the Swift SDK is ~90% feature complete. I also have significant progress made on the Capacitor Plugin (Phase 3) and sample app since I'm developing this in conjunction with the native SDKs. However, one bottleneck that I ran into while developing the Capacitor Plugin and Sample App is that the implementation of the native SDKs has had to change a bit to account for the inherent platform specific differences since I want to keep the SDKs interface as similar as possible. This is why I held back on releasing the Kotlin SDK / Swift SDK until I was confident that the implementation and architecture would stay the same.

I initially estimated completion of the 3 phases by the end of the year and I think it is still a realistic estimate for when the core functionality for everything will be completed. However, it may take me into January to finalize the last remaining steps, which will be to add some Unit & E2E Tests, Add Documentation, and then add release cycles to publish the packages on Maven Central, SPM, and NPM respectively.

**Comment by ItsChaceD** [comment]
Also, I am planning on turning this repo into a monorepo (with Kotlin SDK, Swift SDK, Capacitor Plugin, and Sample App) to allow for easier dependency management and streamlined CI/CD, so just watch this repo for changes!

**Comment by 0x3639** [comment]
Thank you very much for your contribution to the community.  We really appreciate your efforts!  I will update the status summary in the forum.
